export const CustomerService = {
    getCustomersData() {
        return [
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00001',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00002',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00003',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00004',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00005',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00005',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00006',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00007',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00008',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00009',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00010',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00011',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00012',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00013',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00014',
                in_charge: 'Israel Israeli',
            },
            {
                telephone: '456897853',
                code: 'f230fh0g3',
                name: 'שם של לקוח כלשהו',
                type: 'עסקי',
                selected_product: 'אליהו הנביא',
                status: 'פעיל',
                address: 'דוד המלך 42, רחובות',
                open_processes: 4,
                exception_processes: 0,
                open_tasks: 12,
                exception_tasks: 0,
                rating: 'רגיל',
                domain: 'שם של תחום',
                id: '00015',
                in_charge: 'Israel Israeli',
            },
        ];
    },

    getCustomersMini() {
        return Promise.resolve(this.getCustomersData().slice(0, 5));
    },

    getCustomersSmall() {
        return Promise.resolve(this.getCustomersData().slice(0, 10));
    },

    getCustomers() {
        return Promise.resolve(this.getCustomersData());
    },

    getCustomersWithOrdersSmall() {
        return Promise.resolve(this.getCustomersWithOrdersData().slice(0, 10));
    },

    getCustomersWithOrders() {
        return Promise.resolve(this.getCustomersWithOrdersData());
    }
};
