export default function mapTask(task) {
  const is_open = Math.random() < 0.5;
  return {
    name: task.id,
    task_number: task.id,
    process_number: "10",
    task_type: task.task_type?.name,
    family: task.family?.value,
    stage: task.stage?.name,
    sla: task.sla?.sla,
    days_for_closing: task.sla?.days_for_closing,
    contact: "שלומי שבת",
    contact_id: "795",
    state: task.state?.value, //is_open ? 'פתוח' : 'סגור',
    status: task.status?.value, //is_open ? 'פתוח' : 'סגור',
    is_open: task.status?.value == "open",
    due_date: task.sla?.due_date,
    open_date: task.started_at,
    owner: task.owner?.name,
    team: "אגף רישוי ופיקוח (הנדסה)",
    customer: "טיילור סוויפט",
    call: "כן",
    close_date: is_open ? "" : "11/12/23",
    last_change: "11/11/22 10:23",
    remarks: "תוכן של הערה שכתובה יפה מאוד",
    service_number: task.entity?.id,
    description: task.description,
    notes: task.notes,
    location: {
      house_number: "12",
      apartment: "42",
      entrance: "ב",
      street: "שמעון פרס",
      city: "כוכב יאיר",
      country: "ישראל",
      zip: "1234567",
    },
    site: {
      name: "מועצה דתית בית הכנסת",
      contact: "שלומי שבת",
      contact_id: "795",
      contact_role: "אחראי תברואה",
      phone: "054-1234567",
      email: "mailmail@mailmail.com",
      type: "ציבורי",
    },
  };
}
